"""Export en_core_web_sm's attribute-ruler rules to src/parser/attributeRules.js.

The attribute ruler is where spaCy's English pipeline gets coarse POS (pos_),
morphology and a few lemma overrides from fine-grained tags. Rules are kept in
their original order: spaCy applies them in that order, so a later matching
rule overrides an earlier one. The lemmatizer needs MORPH to recognize base
forms.

Usage: python util/export_attribute_rules.py
"""

import json
import pathlib

import spacy

OUT = pathlib.Path(__file__).resolve().parent.parent / "src/parser/attributeRules.js"

# Token-pattern keys and value operators src/parser/attributeRuler.js supports.
KEYS = {"TAG", "LOWER", "DEP", "IS_SPACE"}
OPS = {"IN", "NOT_IN", "REGEX"}


def check_pattern(pattern):
    for spec in pattern:
        assert set(spec) <= KEYS, spec
        for value in spec.values():
            if isinstance(value, dict):
                assert set(value) <= OPS, spec


def main():
    nlp = spacy.load("en_core_web_sm")
    rules = []
    for rule in nlp.get_pipe("attribute_ruler").patterns:
        attrs = {k: v for k, v in rule["attrs"].items() if k in ("POS", "LEMMA", "MORPH")}
        if not attrs:
            continue
        for pattern in rule["patterns"]:
            check_pattern(pattern)
        rules.append({"patterns": rule["patterns"], "attrs": attrs, "index": rule.get("index", 0)})

    body = ",\n".join(json.dumps(r, ensure_ascii=False) for r in rules)
    OUT.write_text(
        f"// Generated by util/export_attribute_rules.py from en_core_web_sm {nlp.meta['version']}\n"
        f"// (spaCy {spacy.__version__}). Do not edit by hand.\n"
        "// Each rule: token patterns, the POS/LEMMA/MORPH it sets, and which token of a\n"
        "// multi-token match receives them. Order matters: later rules win.\n"
        f"export const ATTRIBUTE_RULES = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {len(rules)} rules to {OUT}")


if __name__ == "__main__":
    main()
