"""Export spaCy's English tokenizer exceptions to src/tokenizer/exceptions.js.

Only the ORTH of each piece is kept; that is all the tokenizer needs to split.
Whitespace-only keys are dropped because the browser pipeline discards
whitespace tokens.

Usage: python util/export_tokenizer_exceptions.py
"""

import json
import pathlib

import spacy
from spacy.attrs import ORTH
from spacy.lang.en import English

OUT = pathlib.Path(__file__).resolve().parent.parent / "src/tokenizer/exceptions.js"


def main():
    rules = English().tokenizer.rules
    table = {
        key: [piece[ORTH] for piece in pieces]
        for key, pieces in sorted(rules.items())
        if key.strip()
    }
    for key, pieces in table.items():
        assert "".join(pieces) == key, key

    body = json.dumps(table, ensure_ascii=False, indent=0).replace("\n", "")
    OUT.write_text(
        f"// Generated by util/export_tokenizer_exceptions.py from spaCy {spacy.__version__}\n"
        "// (English().tokenizer.rules). Do not edit by hand.\n"
        "// Maps a string to the tokens it must be split into; the pieces always\n"
        "// concatenate back to the key.\n"
        f"export const EXCEPTIONS = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {len(table)} exceptions to {OUT}")


if __name__ == "__main__":
    main()
